const actionTypes = {
  GET_CURRENT_ORDER: 'GET_CURRENT_ORDER',
  SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',
  ORDER_FETCH_ERROR: 'ORDER_FETCH_ERROR',
  IS_FETCHING: 'IS_FETCHING',
  TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
};

export default actionTypes;
